server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: Passw0rd
    url: jdbc:mysql://129.211.82.202:3306/mock_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mybatis/*.xml   #  mapper位置
  configuration:
    map-underscore-to-camel-case: true  # 驼峰转换

logging:
  file:
    name: log/log.log   # 输出日志文件目录（在项目根目录）
  level:
    root: info
    wuhobin: debug

simplebean:
  name: zhangsan